apiVersion: v1
kind: Namespace
metadata:
  name: isolatedtf
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: isolatedtf
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project":"k8s-default", "name":"mohtesting" }'
  }
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
--- 
apiVersion: v1
kind: Pod
metadata:
  name: busybeebox
  namespace: isolatedtf
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project":"k8s-default", "name":"mohtesting" }'
  }
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always